[package]
name = "ordinator-orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
ordinator-contracts = { path = "../ordinator-contracts" }
ordinator-orchestrator-actor-traits = {path = "../ordinator-orchestrator-actor-traits"}
ordinator-scheduling-environment = { path = "../ordinator-scheduling-environment" }
ordinator-total-data-processing = { path = "../ordinator-total-data-processing"}
ordinator-configuration = { path = "../ordinator-configuration"}


ordinator-weekly-actor = { path = "../ordinator-weekly-actor" }
ordinator-project-actor = { path = "../ordinator-project-actor" }
ordinator-daily-actor = { path = "../ordinator-daily-actor" }
ordinator-operational-actor = { path = "../ordinator-operational-actor" }

# From workspace
anyhow.workspace = true 
arc-swap.workspace = true
chrono.workspace =true
dotenvy.workspace = true
serde.workspace = true
serde_json.workspace = true
flume.workspace = true

tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-flame.workspace = true
tracing-subscriber.workspace = true

# Crate specific
file-rotate = "*"
bus.workspace = true

[dev-dependencies]
ordinator-test-support.path = "../ordinator-test-support"


