[workspace]
resolver = "2"
members = [
    "crates/ordinator-actor-core",
    "crates/ordinator-actor-operational",
    "crates/ordinator-actor-weekly",
    "crates/ordinator-actor-daily",
    "crates/ordinator-actor-project",
    "crates/ordinator-api-server",
    "crates/ordinator-configuration",
    "crates/ordinator-contracts",
    "crates/ordinator-orchestrator",
    "crates/ordinator-orchestrator-actor-traits",
    "crates/ordinator-scheduling-environment",
    "crates/ordinator-scheduling-hypergraph",
    "crates/ordinator-total-data-processing",
    "crates/ordinator-test-support",
    "crates/ordinator-system-tests",
]

[package]
name = "ordinator-monorepo"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
ordinator-api-server.path = "crates/ordinator-api-server" 
ordinator-contracts.path = "crates/ordinator-contracts" 
ordinator-orchestrator.path = "crates/ordinator-orchestrator" 
ordinator-scheduling-environment.path = "crates/ordinator-scheduling-environment" 

[dev-dependencies]
ordinator-test-support.path = "crates/ordinator-test-support"

anyhow.workspace = true
chrono.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true

[workspace.package]
version = "0.0.1"
authors = ["Scipo Aps"]
edition = "2024"
publish = false

[profile.dev]
panic = 'abort'
debug = true

[profile.release]
panic = 'abort'
debug = true
strip = "none"

[workspace.dependencies]
anyhow = "*"
bus = "2.4.1"
thiserror = "*"
arc-swap = "*" 
chrono = { version = "*", features = ["serde"] }
chrono-tz = "*"
clap = "*"
colored = "*"
dotenvy = "*"
flume = "*"
itertools ="*"
mockall = "*"
priority-queue = "*"
proptest ="*"
rand = "0.9"
rgb = "*"
serde = { version = "*", features = ["derive"] } 
serde_json = "*"
strum = "*"
strum_macros = "*"
tokio = { version ="*", features = [ "signal", "macros", "rt-multi-thread", "time"] }
toml = "*"
tracing = {version = "*", features = ["valuable"]}
tracing-appender = "*"
tracing-flame = "*"
tracing-subscriber ={version = "*", features = ["std", "fmt", "env-filter", "json", "valuable", "time"]} 
valuable = {version = "*", features = ["derive"]}

[lints.clippy]
new_without_defualt = "allow"

[lints.rust]
non_snake_case = "allow"
