[package]
name = "ordinator-contracts"
version = "0.1.0"
edition = "2024"

[dependencies]
ordinator-scheduling-environment = { path = "../ordinator-scheduling-environment"}
ordinator-daily-actor = { path = "../ordinator-daily-actor" }
ordinator-weekly-actor = { path = "../ordinator-weekly-actor" }
ordinator-project-actor = { path = "../ordinator-project-actor" }
ordinator-operational-actor = { path = "../ordinator-operational-actor" }
ordinator-orchestrator-actor-traits = { path = "../ordinator-orchestrator-actor-traits"}



anyhow={ workspace = true}
arc-swap.workspace = true
chrono = { workspace = true}
clap = {workspace =true}
serde = {workspace=true}
strum.workspace = true
strum_macros.workspace = true
toml = {workspace=true}
tracing = {workspace=true}
utoipa = "*"
ts-rs = "*"
