[package]
name = "ordinator-api-server"
version = "0.1.0"
edition = "2024"


[dependencies]
ordinator-orchestrator = { path = "../ordinator-orchestrator" }
ordinator-contracts = { path = "../ordinator-contracts" }

axum = {version = "*", features = ["macros", "tokio"]}
axum-extra = {version = "*", features = ["query"]}
axum-server = "*"
chrono.workspace = true
tower = "*"
tower-http = { version = "*", features = ["fs"]}
# actix-files = { workspace = true}
# actix-rt = { workspace = true }
# actix-web = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
serde = {workspace = true}
serde_json = {workspace = true}
strum = {workspace = true}
utoipa = {version = "*", features = ["yaml", "axum_extras"]}
utoipa-axum = "*" 
utoipa-swagger-ui = {version = "*", features = ["axum"]}
chrono-tz.workspace = true
ts-rs = "*"

[dev-dependencies]
ordinator-scheduling-environment.path = "../ordinator-scheduling-environment"

# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# tikv-jemallocator = {version = "0.6"}
