[package]
name = "ordinator-api-server"
version = "0.1.0"
edition = "2024"


[dependencies]
ordinator-orchestrator = { path = "../ordinator-orchestrator" }
ordinator-contracts = { path = "../ordinator-contracts" }

# actix-files.workspace = true
# actix-rt.workspace = true 
# actix-web.workspace = true 
anyhow.workspace = true 
axum = {version = "*", features = ["macros", "tokio"]}
axum-extra = {version = "*", features = ["query", "typed-header"]}
axum-server = "*"
argon2 = {version = "0.5.3", features = ["std"]}
jsonwebtoken = {version = "10.2.0", features = ["aws_lc_rs"]}
chrono-tz.workspace = true
chrono.workspace = true
dotenvy.workspace = true 
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true 
tokio.workspace = true 
tower = "*"
tower-http = { version = "*", features = ["fs"]}
tracing.workspace = true 
ts-rs = "*"
utoipa = {version = "*", features = ["yaml", "axum_extras"]}
utoipa-axum = "*" 
utoipa-swagger-ui = {version = "*", features = ["axum"]}
uuid = { version = "1.18.1", features = ["v4"] }
async-trait = "0.1.89"
sqlx = { version = "*", features = ["runtime-tokio", "sqlite"] }

[dev-dependencies]
ordinator-scheduling-environment.path = "../ordinator-scheduling-environment"
toml.workspace = true

# [target.'cfg(not(target_env = "msvc"))'.dependencies]
# tikv-jemallocator = {version = "0.6"}
