// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetNames } from "./AssetNames";

export type LoginResponse = { access_token: string, refresh_token: string, token_type: string, role: string, assets: Array<AssetNames>, };
