# Throttling in milliseconds (ms)

strategic_throttling   = 500
tactical_throttling    = 500
supervisor_throttling  = 500
operational_throttling = 500


# If you did not fix it, it aint fixed. I think that this is the
# best approach that we could have towards this.l
