// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DateTimeDto } from "./DateTimeDto";

export type CreateTechnicianDto = { id: string, resources_string: Array<string>, start: DateTimeDto, finish: DateTimeDto, };
