// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NaiveDateDto } from "./NaiveDateDto";

export type DailyLoad = { work: number, day: NaiveDateDto, };
