// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OperationDto = { activity: bigint, work_remaining: number, work_center: string, number_of_people: bigint, unloading_point_string: string, scheduled_start_date: string | null, };
