// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaySubtable } from "./DaySubtable";
import type { NaiveDateDto } from "./NaiveDateDto";

export type DailyMainTableDto = { days: { [key in NaiveDateDto]?: DaySubtable }, };
