// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdStringDto } from "./IdStringDto";
import type { MaterialStatusDto } from "./MaterialStatusDto";
import type { Percentage } from "./Percentage";
import type { WorkOrderNumberDto } from "./WorkOrderNumberDto";

export type WorkOrderDailyRow = { id: IdStringDto, area: string | null, work_order_number: WorkOrderNumberDto, activity_number: bigint, permit: string | null, material: MaterialStatusDto, icc: string | null, description: string, hands_on_tool_time: number, hours_worked: number, hours_planned: number, percentage_complete: Percentage, };
