# Throttling in milliseconds (ms)

weekly_throttling   = 10
project_throttling    = 10
daily_throttling  = 10
operational_throttling = 10


# If you did not fix it, it aint fixed. I think that this is the
# best approach that we could have towards this.l
