// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetNames } from "./AssetNames";

export type AvailableAssets = { assets: Array<AssetNames>, };
