// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DailyLoad } from "./DailyLoad";

export type DailyLoadingDto = { resources: { [key in string]?: Array<DailyLoad> }, };
