// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a datetime (e.g., 2025-02-20T07:00:00) as a string in RFC3339 format
 */
export type DateTimeDto = string;
