// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkOrderSupervisorRow } from "./WorkOrderSupervisorRow";

export type DaySubtable = { work_order_activities_per_work_center: { [key in string]?: Array<WorkOrderSupervisorRow> }, };
