// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdStringDto } from "./IdStringDto";
import type { WorkOrderSupervisorRow } from "./WorkOrderSupervisorRow";

export type DaySubtable = { work_order_activities_per_id: { [key in IdStringDto]?: Array<WorkOrderSupervisorRow> }, };
