// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a naive date (e.g., 2025-02-20) as a string
 */
export type NaiveDateDto = string;
