// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdDto } from "./IdDto";

export type SupervisorResponseStatusDto = { supervisor_resource: Array<IdDto>, delegated_work_order_activities: number, objective: bigint, };
