// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupervisorResponseStatusDto = { delegated_work_order_activities: number, objective: bigint, };
