// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IdStringDto } from "./IdStringDto";
import type { NaiveDateDto } from "./NaiveDateDto";

export type TechnicianAvailability = { id: IdStringDto, resources: Array<string>, start: NaiveDateDto, end: NaiveDateDto, };
