// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationDto } from "./OperationDto";

export type WorkOrderSingleRowSimpleDto = { work_order_number: bigint, main_work_center: string, operations: Array<OperationDto>, functional_location: string, sch: boolean, awsc: boolean, vendor: boolean, };
