[strategic]
id = "strategic"
asset = "Df"
strategic_options.number_of_removed_work_orders = 25
strategic_options.urgency_weight = 1
strategic_options.resource_penalty_weight = 1000000
strategic_options.clustering_weight = 1000

[[project]]
id = "project"
asset = "Df"
project_options.number_of_removed_work_orders = 25
project_options.urgency = 1
project_options.resource_penalty = 10000000

mtnelec = 3.5
mtninst = 2.5
mtnmech = 4.5
mtncran = 0.0
mtnturb = 3.0
mtntele = 3.0
mtnrous = 3.0
medic = 1.0
mtnlagg = 2.0
mtnpain = 3.0
mtnpipf = 4.0
mtnrigg = 2.0
mtnrope = 3.5
mtnsat = 0.0
mtnscaf = 3.5
inpsite = 3.0
prodlabo = 0.0
prodtech = 5.0
venacco = 0.0
vencomm = 0.0
venelec = 0.0
venhvac = 0.0
veninsp = 0.0
veninst = 0.0
venmech = 0.0
venmete = 0.0
venrope = 0.0
venscaf = 0.0
vensubs = 0.0
vencran = 0.0
qaqcelec = 0.0
qaqcmech = 0.0
qaqcpain = 0.0
wellsupv = 0.0
