use serde::Deserialize;
use serde::Serialize;

#[derive(Serialize, Deserialize)]
pub struct TomlResources
{
    pub medic: f64,
    pub mtncran: f64,
    pub mtnelec: f64,
    pub mtninst: f64,
    pub mtnlagg: f64,
    pub mtnmech: f64,
    pub mtnpain: f64,
    pub mtnpipf: f64,
    pub mtnrigg: f64,
    pub mtnrope: f64,
    pub mtnrous: f64,
    pub mtnsat: f64,
    pub mtnscaf: f64,
    pub mtntele: f64,
    pub mtnturb: f64,
    pub inpsite: f64,
    pub prodlabo: f64,
    pub prodtech: f64,
    pub venacco: f64,
    pub vencomm: f64,
    pub vencran: f64,
    pub venelec: f64,
    pub venhvac: f64,
    pub veninsp: f64,
    pub veninst: f64,
    pub venmech: f64,
    pub venmete: f64,
    pub venrope: f64,
    pub venscaf: f64,
    pub vensubs: f64,
    pub qaqcelec: f64,
    pub qaqcmech: f64,
    pub qaqcpain: f64,
    pub wellsupv: f64,
}
