// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SupervisorResourcesApi = { id: string, resources: Array<string>, availability: [string, string], };
