#!/usr/bin/env fish
# This is the script associated with the `test_complete_system` integration test.
if test (count $argv) -eq 0
    set argv --help
end

argparse h/help 't/ordinator-test=' 'r/ordinator-run-time=' a/average-objectives= o/optimized-binary= -- $argv
or exit
set -g _flag_ordinator_test $_flag_ordinator_test
set -g _flag_ordinator_run_time $_flag_ordinator_run_time
set -g _flag_average_objectives $_flag_average_objectives
if $_flag_optimized_binary
    set -g release --release
end

set current_date (date +%F)
function pkill_ordinator
    printf "\n\033[91mInterrupted! Killing $_flag_ordinator_test\033[0m\n"
    pkill -f $_flag_ordinator_test
    exit 130
end
if test $_flag_help
    echo "Usage: run Ordinator for research tests"
    echo "Options:"
    echo " -h/--help                  Show this help"
    echo " -c/--ordinator-test        Ordinator test case (REQUIRED)"
    echo "                            E.g. master_system_test_0400_work_orders_30_technicians"
    echo " -r/--ordinator-run-time    Number of seconds that Ordinator should run (REQUIRED)"
    echo " -a/--average-objectives    bool, Should average objectives for multiple actors be used (REQUIRED)"
    echo " -o/--optimized-binary      bool, build the executable in release/optimzed mode"
    exit 0
end

trap pkill_ordinator INT TERM

if test -z "$_flag_ordinator_test"
    echo "ERROR: -c/--ordinator-test is required"
    exit 1
end

if test -z "$_flag_ordinator_run_time"
    echo "ERROR: -r/--ordinator-run-time is required"
    exit 1
end

if test "$_flag_ordinator_test"
    rm -f $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log

    set RUST_BACKTRACE full
    cargo test $release --test $_flag_ordinator_test -- --ignored --nocapture 2>temp_output_from_program.log &

    set count 0
    while test ! -f $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log; or test ! (rg "READY" $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log)
        printf "\rWaiting for Ordinator to start: $count seconds"
        sleep 1
        set count (math $count + 1)
    end

    for i in (seq 1 $_flag_ordinator_run_time)
        sleep 1
        printf "\r\033[32mProgress: %ds of %d\033[0m" $i $_flag_ordinator_run_time
    end

    pkill master_system_t

    jq '
      select(.threadName == "TEST_STRATEGIC" and (.fields | has("objective_value")) ) |
      [ 
      .timestamp, 
      .fields.objective_value.objective_value, 
      .fields.objective_value.urgency[1], 
      .fields.objective_value.resource_penalty[1], 
      .fields.objective_value.clustering_value[1]
      ] |
      join(" ")' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | sed 's/"//g' >./scripts/research/data/strategic.dat

    jq '
      select(.threadName == "TEST_TACTICAL" and (.fields | has("objective_value"))) |
      [ 
      .timestamp, 
      .fields.objective_value.objective_value, 
      .fields.objective_value.urgency[1], 
      .fields.objective_value.resource_penalty[1] 
      ] |
      join(" ")' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | sed 's/"//g' >./scripts/research/data/project.dat

    jq '
      select(.threadName == "TEST_SUPERVISOR" and (.fields | has("objective_value"))) |
      [ 
      .timestamp, 
      .fields.objective_value.percent 
      ] |
      join(" ")' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | sed 's/"//g' >./scripts/research/data/supervisor.dat

    if $_flag_average_objectives
        jq '
            select((.threadName | test("TEST_OP*")) and (.fields | has("objective_value"))) | [(.timestamp[0:19] | strptime("%Y-%m-%dT%H:%M:%S") | strftime("%Y-%m-%dT%H:%M:%SZ")), .fields.objective_value.hands_on_tool_time, .threadName]
          ' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | jq -sr '
            group_by(.[0] )  | map([.[0][0],(map(.[1]) | add / length)]) | .[] | "\(.[0]), \(.[1])" 
          ' | sed 's/"//g' >./scripts/research/data/operational-001-01.dat

        gnuplot -e "
          strategic='scripts/research/data/strategic.dat';
          project='scripts/research/data/project.dat';
          supervisor='scripts/research/data/supervisor.dat';
          operational_1='scripts/research/data/operational-001-01.dat';
          operational_2='scripts/research/data/operational-001-02.dat';
          operational_3='scripts/research/data/operational-002-01.dat';
          output_file='$current_date-$_flag_ordinator_test.tex';
        " ./scripts/research/2-by-2-objective-value-plot.gp

    else
        jq '
          select(.threadName == "TEST_OP-001-01" and (.fields | has("objective_value"))) |
          [ 
          .timestamp, 
          .fields.objective_value.hands_on_tool_time, 
          .fields.objective_value.assess, 
          .fields.objective_value.assign, 
          .fields.objective_value.total_work_order_activities 
          ] |
          join(" ")' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | sed 's/"//g' >./scripts/research/data/operational-001-01.dat

        jq '
          select(.threadName == "TEST_OP-001-02" and (.fields | has("objective_value"))) |
          [ 
          .timestamp, 
          .fields.objective_value.hands_on_tool_time, 
          .fields.objective_value.assess, 
          .fields.objective_value.assign, 
          .fields.objective_value.total_work_order_activities 
          ] |
          join(" ")' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | sed 's/"//g' >./scripts/research/data/operational-001-02.dat

        jq '
          select(.threadName == "TEST_OP-002-01" and (.fields | has("objective_value"))) |
          [ 
          .timestamp, 
          .fields.objective_value.hands_on_tool_time, 
          .fields.objective_value.assess, 
          .fields.objective_value.assign, 
          .fields.objective_value.total_work_order_activities 
          ] |
          join(" ")' $ORDINATOR_LOG_DIR/ordinator/ordinator.research.log | sed 's/"//g' >./scripts/research/data/operational-002-01.dat

        gnuplot -e "
          strategic='scripts/research/data/strategic.dat';
          project='scripts/research/data/project.dat';
          supervisor='scripts/research/data/supervisor.dat';
          operational_1='scripts/research/data/operational-001-01.dat';
          operational_2='scripts/research/data/operational-001-02.dat';
          operational_3='scripts/research/data/operational-002-01.dat';
          output_file='$current_date-$_flag_ordinator_test.tex';
        " ./scripts/research/3-by-2-objective-value-plot.gp
    end
end

trap - INT TERM
